# Databricks notebook — STEP 3: typed load RAW -> SILVER (casts per your DDL)

CAT="workspace"; SILVER="cmos_core"; RAW="cmos_core_raw"

LOADS = {}
LOADS["agreements"] = """INSERT INTO {CAT}.{SILVER}.agreements (`external_id`, `principal_lei`, `principal`, `principal_code`, `counterparty`, `counterparty_code`, `counterparty_lei`, `principal_rating`, `counterparty_rating`, `agreement_category`, `groupname`, `base_currency`, `im_legal_review_frequency`, `legal_review_frequency`, `reciprocity`, `counterparty_fixed_mta_values`, `counterparty_fixed_mta_value_ccy`, `counterparty_im_fixed_mta_values`, `counterparty_im_fixed_mta_value_ccy`, `counterparty_fixed_rounding_values`, `counterparty_fixed_rounding_value_ccy`, `counterparty_fixed_threshold_value_ccy`, `counterparty_fixed_threshold_values`, `counterparty_fixed_values`, `counterparty_im`, `counterparty_im_fixed_rounding_value_ccy`, `counterparty_im_fixed_rounding_values`, `counterparty_im_fixed_threshold_value_ccy`, `counterparty_im_fixed_threshold_values`, `counterparty_im_fixed_values`, `counterparty_im_rating_contingent_values`, `counterparty_im_seg_type`, `principal_fixed_mta_value_ccy`, `principal_fixed_mta_values`, `principal_fixed_rounding_value_ccy`, `principal_fixed_rounding_values`, `principal_fixed_threshold_value_ccy`, `principal_fixed_threshold_values`, `principal_fixed_values`, `principal_im`, `principal_im_fixed_mta_value_ccy`, `principal_im_fixed_mta_values`, `principal_im_fixed_rounding_value_ccy`, `principal_im_fixed_rounding_values`, `principal_im_fixed_threshold_value_ccy`, `principal_im_fixed_threshold_values`, `principal_im_fixed_values`, `principal_im_rating_contingent_values`, `principal_im_seg_type`, `principal_industry`, `principal_agreement_ia`, `counterparty_agreement_ia`, `agreement_date`, `agreement_id`, `agreement_status`, `agreement_description`, `agreement_type`, `agreementgroupcode`, `counterparty_seg_type`, `principal_seg_type`, `segregation`, `linkage_set`, `assets`, `custodian`, `simm_principal_calculation_currency`, `simm_cp_calculation_currency`, `rescued_data`, `reporting_date`, `agreement_name`, `region`, `principal_termination_currency`, `counterparty_termination_currency`, `PARTITIONED`)
SELECT CAST(`external_id` AS STRING) AS `external_id`,
       CAST(`principal_lei` AS STRING) AS `principal_lei`,
       CAST(`principal` AS STRING) AS `principal`,
       CAST(`principal_code` AS STRING) AS `principal_code`,
       CAST(`counterparty` AS STRING) AS `counterparty`,
       CAST(`counterparty_code` AS STRING) AS `counterparty_code`,
       CAST(`counterparty_lei` AS STRING) AS `counterparty_lei`,
       CAST(`principal_rating` AS STRING) AS `principal_rating`,
       CAST(`counterparty_rating` AS STRING) AS `counterparty_rating`,
       CAST(`agreement_category` AS STRING) AS `agreement_category`,
       CAST(`groupname` AS STRING) AS `groupname`,
       CAST(`base_currency` AS STRING) AS `base_currency`,
       CAST(`im_legal_review_frequency` AS STRING) AS `im_legal_review_frequency`,
       CAST(`legal_review_frequency` AS STRING) AS `legal_review_frequency`,
       CAST(`reciprocity` AS STRING) AS `reciprocity`,
       CAST(`counterparty_fixed_mta_values` AS DECIMAL(38,10)) AS `counterparty_fixed_mta_values`,
       CAST(`counterparty_fixed_mta_value_ccy` AS STRING) AS `counterparty_fixed_mta_value_ccy`,
       CAST(`counterparty_im_fixed_mta_values` AS DECIMAL(38,10)) AS `counterparty_im_fixed_mta_values`,
       CAST(`counterparty_im_fixed_mta_value_ccy` AS STRING) AS `counterparty_im_fixed_mta_value_ccy`,
       CAST(`counterparty_fixed_rounding_values` AS DECIMAL(38,10)) AS `counterparty_fixed_rounding_values`,
       CAST(`counterparty_fixed_rounding_value_ccy` AS STRING) AS `counterparty_fixed_rounding_value_ccy`,
       CAST(`counterparty_fixed_threshold_value_ccy` AS STRING) AS `counterparty_fixed_threshold_value_ccy`,
       CAST(`counterparty_fixed_threshold_values` AS DECIMAL(38,10)) AS `counterparty_fixed_threshold_values`,
       CAST(`counterparty_fixed_values` AS DECIMAL(38,10)) AS `counterparty_fixed_values`,
       CAST(`counterparty_im` AS STRING) AS `counterparty_im`,
       CAST(`counterparty_im_fixed_rounding_value_ccy` AS STRING) AS `counterparty_im_fixed_rounding_value_ccy`,
       CAST(`counterparty_im_fixed_rounding_values` AS DECIMAL(38,10)) AS `counterparty_im_fixed_rounding_values`,
       CAST(`counterparty_im_fixed_threshold_value_ccy` AS STRING) AS `counterparty_im_fixed_threshold_value_ccy`,
       CAST(`counterparty_im_fixed_threshold_values` AS DECIMAL(38,10)) AS `counterparty_im_fixed_threshold_values`,
       CAST(`counterparty_im_fixed_values` AS DECIMAL(38,10)) AS `counterparty_im_fixed_values`,
       CAST(`counterparty_im_rating_contingent_values` AS STRING) AS `counterparty_im_rating_contingent_values`,
       CAST(`counterparty_im_seg_type` AS STRING) AS `counterparty_im_seg_type`,
       CAST(`principal_fixed_mta_value_ccy` AS STRING) AS `principal_fixed_mta_value_ccy`,
       CAST(`principal_fixed_mta_values` AS DECIMAL(38,10)) AS `principal_fixed_mta_values`,
       CAST(`principal_fixed_rounding_value_ccy` AS STRING) AS `principal_fixed_rounding_value_ccy`,
       CAST(`principal_fixed_rounding_values` AS DECIMAL(38,10)) AS `principal_fixed_rounding_values`,
       CAST(`principal_fixed_threshold_value_ccy` AS STRING) AS `principal_fixed_threshold_value_ccy`,
       CAST(`principal_fixed_threshold_values` AS DECIMAL(38,10)) AS `principal_fixed_threshold_values`,
       CAST(`principal_fixed_values` AS DECIMAL(38,10)) AS `principal_fixed_values`,
       CAST(`principal_im` AS STRING) AS `principal_im`,
       CAST(`principal_im_fixed_mta_value_ccy` AS STRING) AS `principal_im_fixed_mta_value_ccy`,
       CAST(`principal_im_fixed_mta_values` AS DECIMAL(38,10)) AS `principal_im_fixed_mta_values`,
       CAST(`principal_im_fixed_rounding_value_ccy` AS STRING) AS `principal_im_fixed_rounding_value_ccy`,
       CAST(`principal_im_fixed_rounding_values` AS DECIMAL(38,10)) AS `principal_im_fixed_rounding_values`,
       CAST(`principal_im_fixed_threshold_value_ccy` AS STRING) AS `principal_im_fixed_threshold_value_ccy`,
       CAST(`principal_im_fixed_threshold_values` AS DECIMAL(38,10)) AS `principal_im_fixed_threshold_values`,
       CAST(`principal_im_fixed_values` AS DECIMAL(38,10)) AS `principal_im_fixed_values`,
       CAST(`principal_im_rating_contingent_values` AS STRING) AS `principal_im_rating_contingent_values`,
       CAST(`principal_im_seg_type` AS STRING) AS `principal_im_seg_type`,
       CAST(`principal_industry` AS STRING) AS `principal_industry`,
       CAST(`principal_agreement_ia` AS STRING) AS `principal_agreement_ia`,
       CAST(`counterparty_agreement_ia` AS STRING) AS `counterparty_agreement_ia`,
       CAST(`agreement_date` AS DATE) AS `agreement_date`,
       CAST(`agreement_id` AS STRING) AS `agreement_id`,
       CAST(`agreement_status` AS STRING) AS `agreement_status`,
       CAST(`agreement_description` AS STRING) AS `agreement_description`,
       CAST(`agreement_type` AS STRING) AS `agreement_type`,
       CAST(`agreementgroupcode` AS STRING) AS `agreementgroupcode`,
       CAST(`counterparty_seg_type` AS STRING) AS `counterparty_seg_type`,
       CAST(`principal_seg_type` AS STRING) AS `principal_seg_type`,
       CAST(`segregation` AS STRING) AS `segregation`,
       CAST(`linkage_set` AS STRING) AS `linkage_set`,
       CAST(`assets` AS STRING) AS `assets`,
       CAST(`custodian` AS STRING) AS `custodian`,
       CAST(`simm_principal_calculation_currency` AS STRING) AS `simm_principal_calculation_currency`,
       CAST(`simm_cp_calculation_currency` AS STRING) AS `simm_cp_calculation_currency`,
       CAST(`rescued_data` AS STRING) AS `rescued_data`,
       CAST(`reporting_date` AS DATE) AS `reporting_date`,
       CAST(`agreement_name` AS STRING) AS `agreement_name`,
       CAST(`region` AS STRING) AS `region`,
       CAST(`principal_termination_currency` AS STRING) AS `principal_termination_currency`,
       CAST(`counterparty_termination_currency` AS STRING) AS `counterparty_termination_currency`,
       CAST(NULL AS BY) AS `PARTITIONED`
FROM {CAT}.{RAW}.agreements"""

LOADS["organization"] = """INSERT INTO {CAT}.{SILVER}.organization (`parent_id`, `petrid`, `org_lei`, `parent_lei`, `parent_name`, `internal_rating`, `internal_flag`, `rescued_data`, `reporting_date`, `PARTITIONED`)
SELECT CAST(`parent_id` AS STRING) AS `parent_id`,
       CAST(`petrid` AS STRING) AS `petrid`,
       CAST(`org_lei` AS STRING) AS `org_lei`,
       CAST(`parent_lei` AS STRING) AS `parent_lei`,
       CAST(`parent_name` AS STRING) AS `parent_name`,
       CAST(`internal_rating` AS STRING) AS `internal_rating`,
       CAST(`internal_flag` AS STRING) AS `internal_flag`,
       CAST(`rescued_data` AS STRING) AS `rescued_data`,
       CAST(`reporting_date` AS DATE) AS `reporting_date`,
       CAST(NULL AS BY) AS `PARTITIONED`
FROM {CAT}.{RAW}.organization"""

LOADS["trades"] = """INSERT INTO {CAT}.{SILVER}.trades (`trade_identifier_party_a`, `trade_identifier_2_party_a`, `trade_date`, `effective_date`, `maturity_date`, `party_a_branch_name`, `party_b_branch_name`, `strike_price`, `buy_or_sell`, `put_or_call`, `exchanged_notional_1_amount`, `exchanged_notional_1_currency`, `exchanged_notional_2_amount`, `exchanged_notional_2_currency`, `valuation_base_currency`, `valuation_date`, `underlying`, `external_id`, `valuation_base_currency_amount_t_1`, `margin_type`, `settlement_date`, `agreement_name`, `ims_portfolio`, `ims_desk`, `model`, `pai`, `pai_rate`, `source_system`, `product_type`, `trade_identifier_party_b`, `applicable_agreements`, `rescued_data`, `reporting_date`, `PARTITIONED`)
SELECT CAST(`trade_identifier_party_a` AS STRING) AS `trade_identifier_party_a`,
       CAST(`trade_identifier_2_party_a` AS STRING) AS `trade_identifier_2_party_a`,
       CAST(`trade_date` AS DATE) AS `trade_date`,
       CAST(`effective_date` AS DATE) AS `effective_date`,
       CAST(`maturity_date` AS DATE) AS `maturity_date`,
       CAST(`party_a_branch_name` AS STRING) AS `party_a_branch_name`,
       CAST(`party_b_branch_name` AS STRING) AS `party_b_branch_name`,
       CAST(`strike_price` AS DECIMAL(38,10)) AS `strike_price`,
       CAST(`buy_or_sell` AS STRING) AS `buy_or_sell`,
       CAST(`put_or_call` AS STRING) AS `put_or_call`,
       CAST(`exchanged_notional_1_amount` AS DECIMAL(38,10)) AS `exchanged_notional_1_amount`,
       CAST(`exchanged_notional_1_currency` AS STRING) AS `exchanged_notional_1_currency`,
       CAST(`exchanged_notional_2_amount` AS DECIMAL(38,10)) AS `exchanged_notional_2_amount`,
       CAST(`exchanged_notional_2_currency` AS STRING) AS `exchanged_notional_2_currency`,
       CAST(`valuation_base_currency` AS STRING) AS `valuation_base_currency`,
       CAST(`valuation_date` AS DATE) AS `valuation_date`,
       CAST(`underlying` AS STRING) AS `underlying`,
       CAST(`external_id` AS STRING) AS `external_id`,
       CAST(`valuation_base_currency_amount_t_1` AS DECIMAL(38,10)) AS `valuation_base_currency_amount_t_1`,
       CAST(`margin_type` AS STRING) AS `margin_type`,
       CAST(`settlement_date` AS DATE) AS `settlement_date`,
       CAST(`agreement_name` AS STRING) AS `agreement_name`,
       CAST(`ims_portfolio` AS STRING) AS `ims_portfolio`,
       CAST(`ims_desk` AS STRING) AS `ims_desk`,
       CAST(`model` AS STRING) AS `model`,
       CAST(`pai` AS DECIMAL(38,10)) AS `pai`,
       CAST(`pai_rate` AS DECIMAL(18,8)) AS `pai_rate`,
       CAST(`source_system` AS STRING) AS `source_system`,
       CAST(`product_type` AS STRING) AS `product_type`,
       CAST(`trade_identifier_party_b` AS STRING) AS `trade_identifier_party_b`,
       CAST(`applicable_agreements` AS STRING) AS `applicable_agreements`,
       CAST(`rescued_data` AS STRING) AS `rescued_data`,
       CAST(`reporting_date` AS DATE) AS `reporting_date`,
       CAST(NULL AS BY) AS `PARTITIONED`
FROM {CAT}.{RAW}.trades"""

LOADS["repo_trades"] = """INSERT INTO {CAT}.{SILVER}.repo_trades (`trade_identifier_party_a`, `trade_identifier_2_party_a`, `trade_date`, `start_date`, `end_date`, `party_a_branch_name`, `party_b_branch_name`, `valuation_date`, `underlying`, `external_id`, `settlement_date`, `ims_portfolio`, `ims_desk`, `source_system`, `product_type`, `rescued_data`, `reporting_date`, `PARTITIONED`)
SELECT CAST(`trade_identifier_party_a` AS STRING) AS `trade_identifier_party_a`,
       CAST(`trade_identifier_2_party_a` AS STRING) AS `trade_identifier_2_party_a`,
       CAST(`trade_date` AS DATE) AS `trade_date`,
       CAST(`start_date` AS DATE) AS `start_date`,
       CAST(`end_date` AS DATE) AS `end_date`,
       CAST(`party_a_branch_name` AS STRING) AS `party_a_branch_name`,
       CAST(`party_b_branch_name` AS STRING) AS `party_b_branch_name`,
       CAST(`valuation_date` AS DATE) AS `valuation_date`,
       CAST(`underlying` AS STRING) AS `underlying`,
       CAST(`external_id` AS STRING) AS `external_id`,
       CAST(`settlement_date` AS DATE) AS `settlement_date`,
       CAST(`ims_portfolio` AS STRING) AS `ims_portfolio`,
       CAST(`ims_desk` AS STRING) AS `ims_desk`,
       CAST(`source_system` AS STRING) AS `source_system`,
       CAST(`product_type` AS STRING) AS `product_type`,
       CAST(`rescued_data` AS STRING) AS `rescued_data`,
       CAST(`reporting_date` AS DATE) AS `reporting_date`,
       CAST(NULL AS BY) AS `PARTITIONED`
FROM {CAT}.{RAW}.repo_trades"""

LOADS["daily_exposure"] = """INSERT INTO {CAT}.{SILVER}.daily_exposure (`principal_agreement_level_ia`, `counterparty_agreement_level_ia`, `base_threshold_principal`, `base_threshold_principal_im`, `base_threshold_counterparty`, `base_threshold_counterparty_im`, `base_min_transfer_principal`, `base_min_transfer_principal_im`, `base_min_transfer_counterparty`, `base_min_transfer_counterparty_im`, `base_principal_i_a`, `base_counterparty_external_ia`, `base_counterparty_i_a`, `counterparty_rounding`, `principal_rounding`, `itm_exposure`, `otm_exposure`, `base_total_exposure_amount`, `action`, `agreed_amount`, `base_call_amount`, `booked_amount_first_leg`, `booked_amount_second_leg`, `call_status`, `counterparty_amount`, `reporting_call_amount`, `model`, `agreement_id`, `event_id`, `external_id`, `instrument_id`, `margin_type`, `reporting_currency`, `counterparty_im_rounding`, `principal_im_rounding`, `im_requirement`, `event_date`, `counterparty`, `agreement_description`, `rescued_data`, `reporting_date`, `PARTITIONED`)
SELECT CAST(`principal_agreement_level_ia` AS DECIMAL(38,10)) AS `principal_agreement_level_ia`,
       CAST(`counterparty_agreement_level_ia` AS DECIMAL(38,10)) AS `counterparty_agreement_level_ia`,
       CAST(`base_threshold_principal` AS DECIMAL(38,10)) AS `base_threshold_principal`,
       CAST(`base_threshold_principal_im` AS DECIMAL(38,10)) AS `base_threshold_principal_im`,
       CAST(`base_threshold_counterparty` AS DECIMAL(38,10)) AS `base_threshold_counterparty`,
       CAST(`base_threshold_counterparty_im` AS DECIMAL(38,10)) AS `base_threshold_counterparty_im`,
       CAST(`base_min_transfer_principal` AS DECIMAL(38,10)) AS `base_min_transfer_principal`,
       CAST(`base_min_transfer_principal_im` AS DECIMAL(38,10)) AS `base_min_transfer_principal_im`,
       CAST(`base_min_transfer_counterparty` AS DECIMAL(38,10)) AS `base_min_transfer_counterparty`,
       CAST(`base_min_transfer_counterparty_im` AS DECIMAL(38,10)) AS `base_min_transfer_counterparty_im`,
       CAST(`base_principal_i_a` AS DECIMAL(38,10)) AS `base_principal_i_a`,
       CAST(`base_counterparty_external_ia` AS DECIMAL(38,10)) AS `base_counterparty_external_ia`,
       CAST(`base_counterparty_i_a` AS DECIMAL(38,10)) AS `base_counterparty_i_a`,
       CAST(`counterparty_rounding` AS DECIMAL(38,10)) AS `counterparty_rounding`,
       CAST(`principal_rounding` AS DECIMAL(38,10)) AS `principal_rounding`,
       CAST(`itm_exposure` AS DECIMAL(38,10)) AS `itm_exposure`,
       CAST(`otm_exposure` AS DECIMAL(38,10)) AS `otm_exposure`,
       CAST(`base_total_exposure_amount` AS DECIMAL(38,10)) AS `base_total_exposure_amount`,
       CAST(`action` AS STRING) AS `action`,
       CAST(`agreed_amount` AS DECIMAL(38,10)) AS `agreed_amount`,
       CAST(`base_call_amount` AS DECIMAL(38,10)) AS `base_call_amount`,
       CAST(`booked_amount_first_leg` AS DECIMAL(38,10)) AS `booked_amount_first_leg`,
       CAST(`booked_amount_second_leg` AS DECIMAL(38,10)) AS `booked_amount_second_leg`,
       CAST(`call_status` AS STRING) AS `call_status`,
       CAST(`counterparty_amount` AS DECIMAL(38,10)) AS `counterparty_amount`,
       CAST(`reporting_call_amount` AS DECIMAL(38,10)) AS `reporting_call_amount`,
       CAST(`model` AS STRING) AS `model`,
       CAST(`agreement_id` AS STRING) AS `agreement_id`,
       CAST(`event_id` AS STRING) AS `event_id`,
       CAST(`external_id` AS STRING) AS `external_id`,
       CAST(`instrument_id` AS STRING) AS `instrument_id`,
       CAST(`margin_type` AS STRING) AS `margin_type`,
       CAST(`reporting_currency` AS STRING) AS `reporting_currency`,
       CAST(`counterparty_im_rounding` AS DECIMAL(38,10)) AS `counterparty_im_rounding`,
       CAST(`principal_im_rounding` AS DECIMAL(38,10)) AS `principal_im_rounding`,
       CAST(`im_requirement` AS DECIMAL(38,10)) AS `im_requirement`,
       CAST(`event_date` AS DATE) AS `event_date`,
       CAST(`counterparty` AS STRING) AS `counterparty`,
       CAST(`agreement_description` AS STRING) AS `agreement_description`,
       CAST(`rescued_data` AS STRING) AS `rescued_data`,
       CAST(`reporting_date` AS DATE) AS `reporting_date`,
       CAST(NULL AS BY) AS `PARTITIONED`
FROM {CAT}.{RAW}.daily_exposure"""

LOADS["repo_daily_exposure"] = """INSERT INTO {CAT}.{SILVER}.repo_daily_exposure (`base_threshold_principal`, `base_threshold_counterparty`, `base_min_transfer_principal`, `base_min_transfer_counterparty`, `counterparty_rounding`, `principal_rounding`, `base_total_exposure_amount`, `action`, `agreed_amount`, `base_call_amount`, `booked_amount_first_leg`, `booked_amount_second_leg`, `call_status`, `counterparty_amount`, `reporting_call_amount`, `agreement_id`, `event_id`, `external_id`, `instrument_id`, `margin_type`, `reporting_currency`, `dispute_age`, `rescued_data`, `reporting_date`, `PARTITIONED`)
SELECT CAST(`base_threshold_principal` AS DECIMAL(38,10)) AS `base_threshold_principal`,
       CAST(`base_threshold_counterparty` AS DECIMAL(38,10)) AS `base_threshold_counterparty`,
       CAST(`base_min_transfer_principal` AS DECIMAL(38,10)) AS `base_min_transfer_principal`,
       CAST(`base_min_transfer_counterparty` AS DECIMAL(38,10)) AS `base_min_transfer_counterparty`,
       CAST(`counterparty_rounding` AS DECIMAL(38,10)) AS `counterparty_rounding`,
       CAST(`principal_rounding` AS DECIMAL(38,10)) AS `principal_rounding`,
       CAST(`base_total_exposure_amount` AS DECIMAL(38,10)) AS `base_total_exposure_amount`,
       CAST(`action` AS STRING) AS `action`,
       CAST(`agreed_amount` AS DECIMAL(38,10)) AS `agreed_amount`,
       CAST(`base_call_amount` AS DECIMAL(38,10)) AS `base_call_amount`,
       CAST(`booked_amount_first_leg` AS DECIMAL(38,10)) AS `booked_amount_first_leg`,
       CAST(`booked_amount_second_leg` AS DECIMAL(38,10)) AS `booked_amount_second_leg`,
       CAST(`call_status` AS STRING) AS `call_status`,
       CAST(`counterparty_amount` AS DECIMAL(38,10)) AS `counterparty_amount`,
       CAST(`reporting_call_amount` AS DECIMAL(38,10)) AS `reporting_call_amount`,
       CAST(`agreement_id` AS STRING) AS `agreement_id`,
       CAST(`event_id` AS STRING) AS `event_id`,
       CAST(`external_id` AS STRING) AS `external_id`,
       CAST(`instrument_id` AS STRING) AS `instrument_id`,
       CAST(`margin_type` AS STRING) AS `margin_type`,
       CAST(`reporting_currency` AS STRING) AS `reporting_currency`,
       CAST(`dispute_age` AS INT) AS `dispute_age`,
       CAST(`rescued_data` AS STRING) AS `rescued_data`,
       CAST(`reporting_date` AS DATE) AS `reporting_date`,
       CAST(NULL AS BY) AS `PARTITIONED`
FROM {CAT}.{RAW}.repo_daily_exposure"""

LOADS["disputes"] = """INSERT INTO {CAT}.{SILVER}.disputes (`counterparty`, `description`, `action`, `time`, `base_currency`, `reporting_dispute_amount`, `dispute_age`, `dispute_amount`, `agreement_id`, `event_id`, `rescued_data`, `reporting_date`, `PARTITIONED`)
SELECT CAST(`counterparty` AS STRING) AS `counterparty`,
       CAST(`description` AS STRING) AS `description`,
       CAST(`action` AS STRING) AS `action`,
       CAST(`time` AS TIMESTAMP) AS `time`,
       CAST(`base_currency` AS STRING) AS `base_currency`,
       CAST(`reporting_dispute_amount` AS DECIMAL(38,10)) AS `reporting_dispute_amount`,
       CAST(`dispute_age` AS INT) AS `dispute_age`,
       CAST(`dispute_amount` AS DECIMAL(38,10)) AS `dispute_amount`,
       CAST(`agreement_id` AS STRING) AS `agreement_id`,
       CAST(`event_id` AS STRING) AS `event_id`,
       CAST(`rescued_data` AS STRING) AS `rescued_data`,
       CAST(`reporting_date` AS DATE) AS `reporting_date`,
       CAST(NULL AS BY) AS `PARTITIONED`
FROM {CAT}.{RAW}.disputes"""

LOADS["settlement_instructions"] = """INSERT INTO {CAT}.{SILVER}.settlement_instructions (`agreement_id`, `bucket`, `type`, `asset`, `prc_account_number`, `prc_beneficiary_bank`, `prc_ultimate_custodian`, `cpty_account_number`, `cpty_beneficiary_bank`, `cpty_ultimate_custodian`, `agreement_description`, `business_line`, `counterparty`, `principal`, `rescued_data`, `reporting_date`, `PARTITIONED`)
SELECT CAST(`agreement_id` AS STRING) AS `agreement_id`,
       CAST(`bucket` AS STRING) AS `bucket`,
       CAST(`type` AS STRING) AS `type`,
       CAST(`asset` AS STRING) AS `asset`,
       CAST(`prc_account_number` AS STRING) AS `prc_account_number`,
       CAST(`prc_beneficiary_bank` AS STRING) AS `prc_beneficiary_bank`,
       CAST(`prc_ultimate_custodian` AS STRING) AS `prc_ultimate_custodian`,
       CAST(`cpty_account_number` AS STRING) AS `cpty_account_number`,
       CAST(`cpty_beneficiary_bank` AS STRING) AS `cpty_beneficiary_bank`,
       CAST(`cpty_ultimate_custodian` AS STRING) AS `cpty_ultimate_custodian`,
       CAST(`agreement_description` AS STRING) AS `agreement_description`,
       CAST(`business_line` AS STRING) AS `business_line`,
       CAST(`counterparty` AS STRING) AS `counterparty`,
       CAST(`principal` AS STRING) AS `principal`,
       CAST(`rescued_data` AS STRING) AS `rescued_data`,
       CAST(`reporting_date` AS DATE) AS `reporting_date`,
       CAST(NULL AS BY) AS `PARTITIONED`
FROM {CAT}.{RAW}.settlement_instructions"""

LOADS["collateral_eligibility"] = """INSERT INTO {CAT}.{SILVER}.collateral_eligibility (`agreement_external_id`, `asset_class`, `asset_type`, `maturity_term_from`, `maturity_term_to`, `from_rating_level`, `to_rating_level`, `valuation_haircut`, `rescued_data`, `reporting_day`, `PARTITIONED`)
SELECT CAST(`agreement_external_id` AS STRING) AS `agreement_external_id`,
       CAST(`asset_class` AS STRING) AS `asset_class`,
       CAST(`asset_type` AS STRING) AS `asset_type`,
       CAST(`maturity_term_from` AS DECIMAL(38,10)) AS `maturity_term_from`,
       CAST(`maturity_term_to` AS DECIMAL(38,10)) AS `maturity_term_to`,
       CAST(`from_rating_level` AS STRING) AS `from_rating_level`,
       CAST(`to_rating_level` AS STRING) AS `to_rating_level`,
       CAST(`valuation_haircut` AS DECIMAL(38,10)) AS `valuation_haircut`,
       CAST(`rescued_data` AS STRING) AS `rescued_data`,
       CAST(`reporting_day` AS DATE) AS `reporting_day`,
       CAST(NULL AS BY) AS `PARTITIONED`
FROM {CAT}.{RAW}.collateral_eligibility"""

LOADS["asset_holdings"] = """INSERT INTO {CAT}.{SILVER}.asset_holdings (`issuer`, `description`, `maturity_date`, `classification`, `rating`, `clean_price`, `coupon_accrual`, `factor`, `dirty_price`, `valuation_date`, `lock_up_margin`, `par_amount`, `booking_currency`, `booking_market_value`, `booking_collateral_value`, `haircut`, `internal_policy_reuse`, `reporting_currency`, `reported_market_value`, `reported_collateral_value`, `issue_date`, `agreement_ext_id`, `additional_info_1`, `additional_info_2`, `additional_info_3`, `additional_info_4`, `notation`, `region`, `group`, `counterparty_contact`, `telephone_number`, `fax_number`, `email_address`, `custodian`, `fx_rate`, `margin_type`, `asset_notes1`, `asset_notes2`, `asset_notes3`, `base_ccy`, `base_market_value`, `base_adjusted_collateral_value`, `cpty_country_of_risk`, `instrument_id_type`, `prc_payment_instruction_bucket`, `cpty_payment_instruction_bucket`, `segregation`, `segregation_type`, `gross_calc`, `issuer_country_of_risk`, `prc_account_number`, `prc_beneficiary_bank`, `prc_ultimate_custodian_code`, `prc_ultimate_custodian`, `cpty_account_number`, `cpty_beneficiary_bank`, `cpty_ultimate_custodian_code`, `cpty_ultimate_custodian`, `agreement`, `agreement_category`, `agreement_name`, `asset_class`, `asset_owner`, `asset_type`, `booking_type`, `business_line`, `ccp`, `cqs`, `collateral_status`, `counterparty`, `counterparty_lei`, `counterpartycode`, `counterpartywithcpcode`, `cpty_petrid`, `cpty_jurisdiction`, `cpty_cif_number`, `cpty_internal_flag`, `cpty_internal_rating`, `cpty_bloomberg_ticker`, `cpty_bloomberg_company_id`, `im_rehypothecation_rights`, `instrument_id`, `issue_country_of_risk`, `issuer_code`, `issuer_long_name`, `issuer_rating`, `linkage_set`, `market`, `model`, `pd`, `position`, `prc_petrid`, `prc_jurisdiction`, `prc_cif_number`, `prc_internal_flag`, `prc_bloomberg_ticker`, `prc_bloomberg_company_id`, `price_factor`, `price_source`, `principal`, `principal_lei`, `principalcode`, `rehypothecated`, `rehypothecation_rights`, `rescued_data`, `reporting_date`, `usd_to_cad_rate`, `PARTITIONED`)
SELECT CAST(`issuer` AS STRING) AS `issuer`,
       CAST(`description` AS STRING) AS `description`,
       CAST(`maturity_date` AS DATE) AS `maturity_date`,
       CAST(`classification` AS STRING) AS `classification`,
       CAST(`rating` AS STRING) AS `rating`,
       CAST(`clean_price` AS DECIMAL(38,10)) AS `clean_price`,
       CAST(`coupon_accrual` AS DECIMAL(38,10)) AS `coupon_accrual`,
       CAST(`factor` AS DECIMAL(38,10)) AS `factor`,
       CAST(`dirty_price` AS DECIMAL(38,10)) AS `dirty_price`,
       CAST(`valuation_date` AS DATE) AS `valuation_date`,
       CAST(`lock_up_margin` AS DECIMAL(38,10)) AS `lock_up_margin`,
       CAST(`par_amount` AS DECIMAL(38,10)) AS `par_amount`,
       CAST(`booking_currency` AS STRING) AS `booking_currency`,
       CAST(`booking_market_value` AS DECIMAL(38,10)) AS `booking_market_value`,
       CAST(`booking_collateral_value` AS DECIMAL(38,10)) AS `booking_collateral_value`,
       CAST(`haircut` AS DECIMAL(18,8)) AS `haircut`,
       CAST(`internal_policy_reuse` AS STRING) AS `internal_policy_reuse`,
       CAST(`reporting_currency` AS STRING) AS `reporting_currency`,
       CAST(`reported_market_value` AS DECIMAL(38,10)) AS `reported_market_value`,
       CAST(`reported_collateral_value` AS DECIMAL(38,10)) AS `reported_collateral_value`,
       CAST(`issue_date` AS DATE) AS `issue_date`,
       CAST(`agreement_ext_id` AS STRING) AS `agreement_ext_id`,
       CAST(`additional_info_1` AS STRING) AS `additional_info_1`,
       CAST(`additional_info_2` AS STRING) AS `additional_info_2`,
       CAST(`additional_info_3` AS STRING) AS `additional_info_3`,
       CAST(`additional_info_4` AS STRING) AS `additional_info_4`,
       CAST(`notation` AS STRING) AS `notation`,
       CAST(`region` AS STRING) AS `region`,
       CAST(`group` AS STRING) AS `group`,
       CAST(`counterparty_contact` AS STRING) AS `counterparty_contact`,
       CAST(`telephone_number` AS STRING) AS `telephone_number`,
       CAST(`fax_number` AS STRING) AS `fax_number`,
       CAST(`email_address` AS STRING) AS `email_address`,
       CAST(`custodian` AS STRING) AS `custodian`,
       CAST(`fx_rate` AS DECIMAL(38,10)) AS `fx_rate`,
       CAST(`margin_type` AS STRING) AS `margin_type`,
       CAST(`asset_notes1` AS STRING) AS `asset_notes1`,
       CAST(`asset_notes2` AS STRING) AS `asset_notes2`,
       CAST(`asset_notes3` AS STRING) AS `asset_notes3`,
       CAST(`base_ccy` AS STRING) AS `base_ccy`,
       CAST(`base_market_value` AS DECIMAL(38,10)) AS `base_market_value`,
       CAST(`base_adjusted_collateral_value` AS DECIMAL(38,10)) AS `base_adjusted_collateral_value`,
       CAST(`cpty_country_of_risk` AS STRING) AS `cpty_country_of_risk`,
       CAST(`instrument_id_type` AS STRING) AS `instrument_id_type`,
       CAST(`prc_payment_instruction_bucket` AS STRING) AS `prc_payment_instruction_bucket`,
       CAST(`cpty_payment_instruction_bucket` AS STRING) AS `cpty_payment_instruction_bucket`,
       CAST(`segregation` AS STRING) AS `segregation`,
       CAST(`segregation_type` AS STRING) AS `segregation_type`,
       CAST(`gross_calc` AS STRING) AS `gross_calc`,
       CAST(`issuer_country_of_risk` AS STRING) AS `issuer_country_of_risk`,
       CAST(`prc_account_number` AS STRING) AS `prc_account_number`,
       CAST(`prc_beneficiary_bank` AS STRING) AS `prc_beneficiary_bank`,
       CAST(`prc_ultimate_custodian_code` AS STRING) AS `prc_ultimate_custodian_code`,
       CAST(`prc_ultimate_custodian` AS STRING) AS `prc_ultimate_custodian`,
       CAST(`cpty_account_number` AS STRING) AS `cpty_account_number`,
       CAST(`cpty_beneficiary_bank` AS STRING) AS `cpty_beneficiary_bank`,
       CAST(`cpty_ultimate_custodian_code` AS STRING) AS `cpty_ultimate_custodian_code`,
       CAST(`cpty_ultimate_custodian` AS STRING) AS `cpty_ultimate_custodian`,
       CAST(`agreement` AS STRING) AS `agreement`,
       CAST(`agreement_category` AS STRING) AS `agreement_category`,
       CAST(`agreement_name` AS STRING) AS `agreement_name`,
       CAST(`asset_class` AS STRING) AS `asset_class`,
       CAST(`asset_owner` AS STRING) AS `asset_owner`,
       CAST(`asset_type` AS STRING) AS `asset_type`,
       CAST(`booking_type` AS STRING) AS `booking_type`,
       CAST(`business_line` AS STRING) AS `business_line`,
       CAST(`ccp` AS STRING) AS `ccp`,
       CAST(`cqs` AS STRING) AS `cqs`,
       CAST(`collateral_status` AS STRING) AS `collateral_status`,
       CAST(`counterparty` AS STRING) AS `counterparty`,
       CAST(`counterparty_lei` AS STRING) AS `counterparty_lei`,
       CAST(`counterpartycode` AS STRING) AS `counterpartycode`,
       CAST(`counterpartywithcpcode` AS STRING) AS `counterpartywithcpcode`,
       CAST(`cpty_petrid` AS STRING) AS `cpty_petrid`,
       CAST(`cpty_jurisdiction` AS STRING) AS `cpty_jurisdiction`,
       CAST(`cpty_cif_number` AS STRING) AS `cpty_cif_number`,
       CAST(`cpty_internal_flag` AS STRING) AS `cpty_internal_flag`,
       CAST(`cpty_internal_rating` AS STRING) AS `cpty_internal_rating`,
       CAST(`cpty_bloomberg_ticker` AS STRING) AS `cpty_bloomberg_ticker`,
       CAST(`cpty_bloomberg_company_id` AS STRING) AS `cpty_bloomberg_company_id`,
       CAST(`im_rehypothecation_rights` AS STRING) AS `im_rehypothecation_rights`,
       CAST(`instrument_id` AS STRING) AS `instrument_id`,
       CAST(`issue_country_of_risk` AS STRING) AS `issue_country_of_risk`,
       CAST(`issuer_code` AS STRING) AS `issuer_code`,
       CAST(`issuer_long_name` AS STRING) AS `issuer_long_name`,
       CAST(`issuer_rating` AS STRING) AS `issuer_rating`,
       CAST(`linkage_set` AS STRING) AS `linkage_set`,
       CAST(`market` AS STRING) AS `market`,
       CAST(`model` AS STRING) AS `model`,
       CAST(`pd` AS DECIMAL(18,8)) AS `pd`,
       CAST(`position` AS STRING) AS `position`,
       CAST(`prc_petrid` AS STRING) AS `prc_petrid`,
       CAST(`prc_jurisdiction` AS STRING) AS `prc_jurisdiction`,
       CAST(`prc_cif_number` AS STRING) AS `prc_cif_number`,
       CAST(`prc_internal_flag` AS STRING) AS `prc_internal_flag`,
       CAST(`prc_bloomberg_ticker` AS STRING) AS `prc_bloomberg_ticker`,
       CAST(`prc_bloomberg_company_id` AS STRING) AS `prc_bloomberg_company_id`,
       CAST(`price_factor` AS DECIMAL(38,10)) AS `price_factor`,
       CAST(`price_source` AS STRING) AS `price_source`,
       CAST(`principal` AS STRING) AS `principal`,
       CAST(`principal_lei` AS STRING) AS `principal_lei`,
       CAST(`principalcode` AS STRING) AS `principalcode`,
       CAST(`rehypothecated` AS STRING) AS `rehypothecated`,
       CAST(`rehypothecation_rights` AS STRING) AS `rehypothecation_rights`,
       CAST(`rescued_data` AS STRING) AS `rescued_data`,
       CAST(`reporting_date` AS DATE) AS `reporting_date`,
       CAST(`usd_to_cad_rate` AS DECIMAL(38,10)) AS `usd_to_cad_rate`,
       CAST(NULL AS BY) AS `PARTITIONED`
FROM {CAT}.{RAW}.asset_holdings"""

LOADS["asset_settlements"] = """INSERT INTO {CAT}.{SILVER}.asset_settlements (`instrument_id`, `currency`, `creation_date`, `settlement_date`, `actual_settlement_date`, `nominal_amount`, `reported_collateral_value`, `reporting_currency`, `payment_instructions_bucket`, `external_id`, `instrument_id_type`, `issuer`, `issued_amount`, `asset_class`, `asset_type`, `booking_market_value`, `booking_type`, `collateral_status`, `movement`, `rescued_data`, `reporting_date`, `PARTITIONED`)
SELECT CAST(`instrument_id` AS STRING) AS `instrument_id`,
       CAST(`currency` AS STRING) AS `currency`,
       CAST(`creation_date` AS DATE) AS `creation_date`,
       CAST(`settlement_date` AS DATE) AS `settlement_date`,
       CAST(`actual_settlement_date` AS DATE) AS `actual_settlement_date`,
       CAST(`nominal_amount` AS DECIMAL(38,10)) AS `nominal_amount`,
       CAST(`reported_collateral_value` AS DECIMAL(38,10)) AS `reported_collateral_value`,
       CAST(`reporting_currency` AS STRING) AS `reporting_currency`,
       CAST(`payment_instructions_bucket` AS STRING) AS `payment_instructions_bucket`,
       CAST(`external_id` AS STRING) AS `external_id`,
       CAST(`instrument_id_type` AS STRING) AS `instrument_id_type`,
       CAST(`issuer` AS STRING) AS `issuer`,
       CAST(`issued_amount` AS DECIMAL(38,10)) AS `issued_amount`,
       CAST(`asset_class` AS STRING) AS `asset_class`,
       CAST(`asset_type` AS STRING) AS `asset_type`,
       CAST(`booking_market_value` AS DECIMAL(38,10)) AS `booking_market_value`,
       CAST(`booking_type` AS STRING) AS `booking_type`,
       CAST(`collateral_status` AS STRING) AS `collateral_status`,
       CAST(`movement` AS STRING) AS `movement`,
       CAST(`rescued_data` AS STRING) AS `rescued_data`,
       CAST(`reporting_date` AS DATE) AS `reporting_date`,
       CAST(NULL AS BY) AS `PARTITIONED`
FROM {CAT}.{RAW}.asset_settlements"""

LOADS["fx_rates"] = """INSERT INTO {CAT}.{SILVER}.fx_rates (`date`, `bid_rate`, `offer_rate`, `ccy`, `rate_type`, `fx_rate_set`)
SELECT CAST(`date` AS DATE) AS `date`,
       CAST(`bid_rate` AS DECIMAL(38,10)) AS `bid_rate`,
       CAST(`offer_rate` AS DECIMAL(38,10)) AS `offer_rate`,
       CAST(`ccy` AS STRING) AS `ccy`,
       CAST(`rate_type` AS STRING) AS `rate_type`,
       CAST(`fx_rate_set` AS STRING) AS `fx_rate_set`
FROM {CAT}.{RAW}.fx_rates"""

for t, stmt in LOADS.items():
    spark.sql(f"TRUNCATE TABLE {CAT}.{SILVER}." + t)
    spark.sql(stmt.format(CAT=CAT, SILVER=SILVER))
    n = spark.table(f"{CAT}.{SILVER}.{t}").count()
    print(f"silver {t}: {n} rows")
