-- Credit-risk business glossary: table + seed data
-- Target: `d4001-centralus-tdvip-creditrisk`.`xvala_core`.`credit_risk_glossary`
-- Catalog name is hyphenated -> every identifier is backtick-quoted.
-- If your schema differs, find/replace the schema name below.

CREATE TABLE IF NOT EXISTS `d4001-centralus-tdvip-creditrisk`.`xvala_core`.`credit_risk_glossary` (
  `token` STRING NOT NULL COMMENT 'Short token / abbreviation key (unique).',
  `canonical_term` STRING COMMENT 'Human-readable canonical business term.',
  `definition` STRING COMMENT 'Approved one-sentence business definition (FIBO/ISDA/Basel-aligned draft until signed off).',
  `category` STRING COMMENT 'Concept category (counterparty, collateral, risk-metric, rating, date, market, general).',
  `owner_domain` STRING COMMENT 'Stewardship domain: credit_risk | reference_data | trades | market_data | shared.',
  `source_standard` STRING COMMENT 'Originating standard: FIBO | ISDA | FpML | Basel | ISO | industry | accounting | convention.',
  `standard_reference` STRING COMMENT 'Honest pointer to the source (e.g. ISO 17442, Basel CRE52, ISDA CSA). No fabricated URIs.',
  `also_seen_as` STRING COMMENT 'Comma-separated physical aliases the name->glossary matcher uses.',
  `status` STRING COMMENT 'Lifecycle: draft | approved | deprecated.',
  `steward` STRING COMMENT 'Named data steward who approved the definition.',
  `notes` STRING COMMENT 'Free-text notes.'
)
USING DELTA
COMMENT 'Credit-risk business glossary (system of record). Seeded from FIBO/ISDA/Basel; human sign-off required before status = approved.'
TBLPROPERTIES ('delta.columnMapping.mode' = 'name');

-- Optional: informational primary key on token (not enforced by Databricks)
-- ALTER TABLE `d4001-centralus-tdvip-creditrisk`.`xvala_core`.`credit_risk_glossary` ADD CONSTRAINT pk_glossary PRIMARY KEY (`token`);

-- Reload seed rows (INSERT OVERWRITE keeps the table definition/comments)
INSERT OVERWRITE `d4001-centralus-tdvip-creditrisk`.`xvala_core`.`credit_risk_glossary`
  (`token`, `canonical_term`, `definition`, `category`, `owner_domain`, `source_standard`, `standard_reference`, `also_seen_as`, `status`, `steward`, `notes`)
VALUES
  ('id', 'identifier', 'A value that uniquely identifies an instance of an entity.', 'general', 'shared', 'convention', NULL, 'ident,idnt', 'draft', NULL, NULL),
  ('cd', 'code', 'A short coded value drawn from a controlled set, classifying an attribute.', 'general', 'shared', 'convention', NULL, 'code', 'draft', NULL, NULL),
  ('nm', 'name', 'The name by which an entity is known.', 'general', 'shared', 'convention', NULL, 'name', 'draft', NULL, NULL),
  ('desc', 'description', 'A free-text description of an entity or attribute.', 'general', 'shared', 'convention', NULL, 'dsc', 'draft', NULL, NULL),
  ('dt', 'date', 'A calendar date (no time component).', 'general', 'shared', 'ISO', 'ISO 8601', 'date', 'draft', NULL, NULL),
  ('ts', 'timestamp', 'A specific point in time, date plus time of day.', 'general', 'shared', 'ISO', 'ISO 8601', 'tmstmp,time', 'draft', NULL, NULL),
  ('amt', 'amount', 'A monetary amount, normally with an associated currency.', 'general', 'shared', 'convention', NULL, 'amnt', 'draft', NULL, NULL),
  ('ccy', 'currency', 'The currency in which a monetary amount is denominated.', 'general', 'shared', 'ISO', 'ISO 4217', 'cur,curr', 'draft', NULL, NULL),
  ('qty', 'quantity', 'A counted or measured quantity.', 'general', 'shared', 'convention', NULL, 'quantity', 'draft', NULL, NULL),
  ('val', 'value', 'A measured or computed value.', 'general', 'shared', 'convention', NULL, 'value', 'draft', NULL, NULL),
  ('pct', 'percent', 'A ratio expressed as a percentage (parts per hundred).', 'general', 'shared', 'convention', NULL, 'perc,percentage', 'draft', NULL, NULL),
  ('num', 'number', 'A numeric identifier or count.', 'general', 'shared', 'convention', NULL, 'no,nbr', 'draft', NULL, NULL),
  ('ref', 'reference', 'A reference pointing to another object or record.', 'general', 'shared', 'convention', NULL, 'rfrnc', 'draft', NULL, NULL),
  ('ind', 'indicator', 'A boolean flag indicating presence/absence of a condition.', 'general', 'shared', 'convention', NULL, 'flag,flg', 'draft', NULL, NULL),
  ('asof', 'as-of date', 'The effective snapshot date to which a row''s values apply.', 'general', 'shared', 'convention', NULL, 'as_of,asofdt', 'draft', NULL, NULL),
  ('bd', 'business date', 'The business (processing) date of a record.', 'general', 'shared', 'convention', NULL, 'busdate,bus_dt', 'draft', NULL, NULL),
  ('cpty', 'counterparty', 'The legal entity that is the other party to a contract or transaction and to which the institution is exposed to credit risk.', 'counterparty', 'reference_data', 'FIBO', 'FIBO: Counterparty', 'cp,ctpy,cpy', 'draft', NULL, 'Core CCR entity; upstream owner = CDO/reference data.'),
  ('le', 'legal entity', 'A legally constituted organisation that can enter into contracts in its own right.', 'counterparty', 'reference_data', 'FIBO', 'FIBO: Legal Entity', 'legalentity', 'draft', NULL, NULL),
  ('lei', 'Legal Entity Identifier', 'A 20-character alphanumeric ISO 17442 code that uniquely identifies a legally distinct entity participating in financial transactions.', 'counterparty', 'reference_data', 'ISO', 'ISO 17442 / GLEIF', 'lei_code', 'draft', NULL, NULL),
  ('bic', 'Bank Identifier Code', 'An ISO 9362 business identifier code (SWIFT code) identifying a financial institution.', 'counterparty', 'reference_data', 'ISO', 'ISO 9362', 'swift', 'draft', NULL, NULL),
  ('guar', 'guarantor', 'A party that undertakes to satisfy the obligation of an obligor if that obligor fails to perform.', 'counterparty', 'reference_data', 'FIBO', 'FIBO: Guarantor', 'grntr,guarantor', 'draft', NULL, NULL),
  ('obligor', 'obligor', 'The party that is obliged to repay a debt or perform a financial obligation.', 'counterparty', 'reference_data', 'Basel', 'Basel CRE', 'oblgr', 'draft', NULL, NULL),
  ('issuer', 'issuer', 'The legal entity that creates, registers and sells a security to fund its operations.', 'counterparty', 'reference_data', 'FIBO', 'FIBO: Issuer', 'iss', 'draft', NULL, NULL),
  ('parent', 'ultimate parent', 'The entity at the top of an ownership hierarchy that controls a counterparty and is not itself controlled by another.', 'counterparty', 'reference_data', 'FIBO', 'FIBO: Ultimate Parent', 'ult_parent,uparent', 'draft', NULL, NULL),
  ('agrmt', 'agreement', 'A legally binding arrangement between parties setting out rights and obligations.', 'collateral', 'credit_risk', 'FIBO', 'FIBO: Master Agreement', 'agr,agrmnt,agreement', 'draft', NULL, NULL),
  ('isda', 'ISDA Master Agreement', 'The standard bilateral framework contract published by ISDA that governs OTC derivative transactions between two parties, including netting and close-out provisions.', 'collateral', 'credit_risk', 'ISDA', 'ISDA Master Agreement', 'isda_ma', 'draft', NULL, NULL),
  ('csa', 'Credit Support Annex', 'An annex to an ISDA Master Agreement documenting collateral terms: thresholds, minimum transfer amounts, eligible collateral and margin frequency.', 'collateral', 'credit_risk', 'ISDA', 'ISDA CSA', 'csa', 'draft', NULL, NULL),
  ('coll', 'collateral', 'Assets pledged by a counterparty to secure an obligation and mitigate credit exposure.', 'collateral', 'credit_risk', 'ISDA', 'FIBO/ISDA: Collateral', 'collat,coll_val', 'draft', NULL, NULL),
  ('net', 'netting set', 'A group of trades with one counterparty under a legally enforceable netting agreement whose exposures may be offset when computing exposure.', 'collateral', 'credit_risk', 'Basel', 'Basel CRE52', 'netting,netset', 'draft', NULL, NULL),
  ('mta', 'Minimum Transfer Amount', 'The smallest collateral amount that may be called or returned under a CSA; movements below it are not exchanged.', 'collateral', 'credit_risk', 'ISDA', 'ISDA CSA', 'min_transfer', 'draft', NULL, NULL),
  ('thr', 'threshold', 'An amount of unsecured exposure a party is permitted under a CSA before collateral must be posted.', 'collateral', 'credit_risk', 'ISDA', 'ISDA CSA', 'threshold,thresh', 'draft', NULL, NULL),
  ('ia', 'Independent Amount', 'Collateral required over and above current mark-to-market exposure, providing an additional cushion (bilateral analogue of initial margin).', 'collateral', 'credit_risk', 'ISDA', 'ISDA CSA', 'indep_amt', 'draft', NULL, NULL),
  ('vm', 'Variation Margin', 'Collateral exchanged to cover the current mark-to-market change in value of outstanding positions.', 'collateral', 'credit_risk', 'ISDA', 'BCBS-IOSCO margin / ISDA', 'var_margin', 'draft', NULL, NULL),
  ('im', 'Initial Margin', 'Collateral posted to cover potential future change in exposure over a close-out period, in addition to variation margin.', 'collateral', 'credit_risk', 'Basel', 'BCBS-IOSCO margin', 'init_margin', 'draft', NULL, NULL),
  ('elig', 'eligible collateral', 'Collateral types permitted under an agreement, subject to defined haircuts.', 'collateral', 'credit_risk', 'ISDA', 'ISDA CSA', 'eligible', 'draft', NULL, NULL),
  ('exp', 'exposure', 'The amount the institution stands to lose on a counterparty if that counterparty defaults.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE', 'expsr,exposure', 'draft', NULL, NULL),
  ('pfe', 'Potential Future Exposure', 'The maximum expected credit exposure over a future horizon at a given confidence level, estimated by simulating market risk factors.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE53', 'pfe', 'draft', NULL, NULL),
  ('epe', 'Expected Positive Exposure', 'The time-weighted average of expected positive exposures over a horizon; an input to CCR capital.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE53', 'epe', 'draft', NULL, NULL),
  ('ene', 'Expected Negative Exposure', 'The time-weighted average of expected exposures from the counterparty''s perspective.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE53', 'ene', 'draft', NULL, NULL),
  ('ead', 'Exposure at Default', 'The expected gross exposure of a facility at the time a counterparty defaults.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE', 'ead', 'draft', NULL, NULL),
  ('ccr', 'Counterparty Credit Risk', 'The risk that the counterparty to a transaction defaults before final settlement when the contract has positive value to the institution.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE51', 'ccr', 'draft', NULL, NULL),
  ('cva', 'Credit Valuation Adjustment', 'An adjustment to the value of a derivative portfolio reflecting the market value of counterparty credit risk.', 'risk-metric', 'credit_risk', 'Basel', 'Basel MAR50', 'cva', 'draft', NULL, NULL),
  ('dva', 'Debit Valuation Adjustment', 'An adjustment reflecting the institution''s own credit risk in the valuation of its liabilities.', 'risk-metric', 'credit_risk', 'accounting', 'IFRS 13', 'dva', 'draft', NULL, NULL),
  ('fva', 'Funding Valuation Adjustment', 'An adjustment for the funding cost or benefit of uncollateralised derivative positions.', 'risk-metric', 'credit_risk', 'industry', 'industry convention', 'fva', 'draft', NULL, NULL),
  ('xva', 'valuation adjustments', 'Collective term for valuation adjustments applied to derivative pricing (CVA, DVA, FVA, MVA, KVA).', 'risk-metric', 'credit_risk', 'industry', 'industry convention', 'xva', 'draft', NULL, NULL),
  ('mtm', 'mark-to-market', 'The current fair value of a position based on prevailing market prices.', 'risk-metric', 'credit_risk', 'convention', NULL, 'mv,marktomarket', 'draft', NULL, 'Also used by market risk / valuations.'),
  ('npv', 'Net Present Value', 'The value today of a stream of future cash flows discounted at an appropriate rate.', 'risk-metric', 'credit_risk', 'convention', NULL, 'npv', 'draft', NULL, 'Shared with valuations / market risk.'),
  ('rwa', 'Risk-Weighted Assets', 'A bank''s assets weighted by credit, market and operational risk, used to determine regulatory capital requirements.', 'risk-metric', 'credit_risk', 'Basel', 'Basel framework', 'rwa', 'draft', NULL, NULL),
  ('saccr', 'Standardised Approach for CCR', 'The Basel method for computing EAD on derivative exposures (replacement cost plus potential future exposure add-on); replaces CEM.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE52', 'sa_ccr,sa-ccr', 'draft', NULL, NULL),
  ('cem', 'Current Exposure Method', 'The legacy Basel approach to derivative exposure (current mark-to-market plus a regulatory add-on); superseded by SA-CCR.', 'risk-metric', 'credit_risk', 'Basel', 'Basel (legacy)', 'cem', 'draft', NULL, NULL),
  ('pd', 'Probability of Default', 'The likelihood that an obligor defaults over a specified time horizon.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE', 'pd', 'draft', NULL, NULL),
  ('lgd', 'Loss Given Default', 'The fraction of an exposure expected to be lost if the obligor defaults, net of recoveries.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE', 'lgd', 'draft', NULL, NULL),
  ('el', 'Expected Loss', 'The anticipated average credit loss over a period, computed as PD x LGD x EAD.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE', 'el', 'draft', NULL, NULL),
  ('var', 'Value at Risk', 'The loss on a portfolio that will not be exceeded over a given horizon at a specified confidence level.', 'risk-metric', 'credit_risk', 'industry', 'Basel MAR (legacy)', 'v_a_r', 'draft', NULL, 'Primarily a market-risk measure; CCR uses related concepts.'),
  ('es', 'Expected Shortfall', 'The average loss in the tail beyond the VaR threshold; the FRTB market-risk capital measure.', 'risk-metric', 'credit_risk', 'Basel', 'Basel MAR (FRTB)', 'expected_shortfall', 'draft', NULL, 'Owner is market risk; listed for cross-reference.'),
  ('trd', 'trade', 'An executed transaction in a financial instrument between two parties.', 'market', 'trades', 'FpML', 'FpML / FIBO: Trade', 'txn,trade,trd', 'draft', NULL, 'Upstream owner = CDO / front office.'),
  ('notional', 'notional', 'The reference (face) amount of a derivative used to calculate payments; generally not exchanged.', 'market', 'trades', 'FpML', 'FpML / FIBO: Notional Amount', 'notnl,nom,notional', 'draft', NULL, NULL),
  ('mat', 'maturity', 'The date on which a contract''s obligations terminate and final payment is due.', 'market', 'trades', 'FIBO', 'FIBO: Maturity Date', 'maturity', 'draft', NULL, NULL),
  ('tenor', 'tenor', 'The remaining time to maturity of an instrument, often expressed in standard buckets (e.g. 0-3M, 1Y, 5Y).', 'market', 'trades', 'convention', NULL, 'tnr,tenor', 'draft', NULL, NULL),
  ('px', 'price', 'The price at which an instrument trades or is valued.', 'market', 'market_data', 'FIX', 'FIX / FIBO: Price', 'price,prc', 'draft', NULL, NULL),
  ('rt', 'rate', 'A rate applied to a notional or balance (e.g. an interest or coupon rate).', 'market', 'market_data', 'FIBO', 'FIBO: Rate', 'rate', 'draft', NULL, NULL),
  ('ir', 'interest rate', 'The rate charged or paid for the use of money, expressed as a percentage per period.', 'market', 'market_data', 'FIBO', 'FIBO: Interest Rate', 'int_rate', 'draft', NULL, NULL),
  ('fx', 'foreign exchange', 'The conversion of one currency into another and the market in which it occurs.', 'market', 'market_data', 'FIBO', 'FIBO: Foreign Exchange', 'fx', 'draft', NULL, NULL),
  ('bps', 'basis points', 'One hundredth of one percent (0.01%); the unit used to quote rates and spreads.', 'market', 'market_data', 'convention', NULL, 'bp,bps', 'draft', NULL, NULL),
  ('spd', 'spread', 'The difference between two prices or rates, such as a credit spread over a benchmark.', 'market', 'market_data', 'convention', NULL, 'sprd,spread', 'draft', NULL, NULL),
  ('pos', 'position', 'The net holding in a financial instrument resulting from trades.', 'market', 'trades', 'convention', NULL, 'position', 'draft', NULL, NULL),
  ('swap', 'interest rate swap', 'A derivative in which two parties exchange streams of cash flows, e.g. fixed for floating interest.', 'market', 'trades', 'FpML', 'FpML / FIBO: Interest Rate Swap', 'irs', 'draft', NULL, NULL),
  ('fwd', 'forward', 'An OTC contract to buy or sell an asset at a future date for a price agreed today.', 'market', 'trades', 'FpML', 'FpML / FIBO: Forward', 'forward', 'draft', NULL, NULL),
  ('opt', 'option', 'A contract granting the right, not the obligation, to buy or sell an asset at a set price.', 'market', 'trades', 'FpML', 'FpML / FIBO: Option', 'option', 'draft', NULL, NULL),
  ('rtg', 'rating', 'An assessment of the creditworthiness of an obligor or instrument on an ordinal scale.', 'rating', 'reference_data', 'FIBO', 'FIBO: Credit Rating', 'rt,rating', 'draft', NULL, NULL),
  ('sov', 'sovereign', 'A national or central government entity acting as issuer or obligor.', 'rating', 'reference_data', 'FIBO', 'FIBO: Sovereign', 'sovereign', 'draft', NULL, NULL),
  ('corp', 'corporate', 'A corporate (non-financial company) issuer or obligor.', 'rating', 'reference_data', 'FIBO', 'FIBO: Corporate', 'corporate', 'draft', NULL, NULL),
  ('nr', 'not rated', 'No external credit rating has been assigned.', 'rating', 'reference_data', 'convention', NULL, 'not_rated', 'draft', NULL, NULL),
  ('sp', 'S&P', 'S&P Global Ratings, a credit rating agency.', 'rating', 'reference_data', 'convention', NULL, 's_and_p,sandp', 'draft', NULL, NULL),
  ('mdy', 'Moody''s', 'Moody''s Investors Service, a credit rating agency.', 'rating', 'reference_data', 'convention', NULL, 'moodys', 'draft', NULL, NULL),
  ('mo', 'month', 'A calendar month, used as a tenor unit.', 'date', 'shared', 'convention', NULL, 'mth,month', 'draft', NULL, NULL),
  ('yr', 'year', 'A calendar year, used as a tenor unit.', 'date', 'shared', 'convention', NULL, 'year,yrs', 'draft', NULL, NULL),
  ('line', 'credit line', 'A counterparty credit/trading line (facility) against which exposure is measured and a limit is set; the grain of the PFE tearsheet.', 'counterparty', 'credit_risk', 'convention', NULL, 'line_id,facility,trading_line', 'draft', NULL, 'Identified like CP_(TDBK)_(AMCQ_C2C).'),
  ('long_name', 'counterparty long name', 'The full descriptive name of the counterparty associated with a line.', 'counterparty', 'reference_data', 'convention', NULL, 'longname,cpty_name', 'draft', NULL, 'Per-line variants seen in asts.'),
  ('line_expiry', 'line expiry date', 'The date on which a credit line / facility expires.', 'date', 'credit_risk', 'convention', NULL, 'lineexpiry,expiry_dt', 'draft', NULL, 'Stored as YYYYMMDD integer in asts.'),
  ('scenario', 'stress scenario', 'A defined set of market conditions applied to compute a stressed exposure.', 'risk-metric', 'credit_risk', 'convention', NULL, 'scen', 'draft', NULL, NULL),
  ('series', 'scenario series', 'A named stress-scenario series under which exposure is computed and reported.', 'risk-metric', 'credit_risk', 'convention', NULL, 'scenario_series', 'draft', NULL, 'Engine codes mapped to display names via scenario xref.'),
  ('time_bucket', 'time bucket', 'A maturity/horizon bucket over which the exposure profile is reported (e.g. 0-3M, 1Y, 5Y).', 'risk-metric', 'credit_risk', 'convention', NULL, 'timebucket,bucket', 'draft', NULL, NULL),
  ('stressed_exposure', 'stressed exposure', 'Counterparty exposure projected under a stress scenario, tested against the PFE limit.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE53 (PFE)', 'stress_exp,stressedexp', 'draft', NULL, NULL),
  ('current_value', 'current exposure', 'The current (unstressed) exposure or mark-to-market value for the line.', 'risk-metric', 'credit_risk', 'convention', NULL, 'current_exp,curr_exposure', 'draft', NULL, NULL),
  ('limit_value', 'exposure limit', 'The approved PFE / exposure limit for a line against which breaches are measured.', 'risk-metric', 'credit_risk', 'Basel', 'Basel CRE (limits)', 'limit,lmt', 'draft', NULL, 'Null on the BASE row in asts.'),
  ('change_vs_current', 'change vs current', 'The change in exposure under a scenario relative to current exposure.', 'risk-metric', 'credit_risk', 'convention', NULL, 'chg_vs_current,delta_exposure', 'draft', NULL, NULL),
  ('excess_amount', 'breach excess amount', 'The dollar amount by which stressed exposure exceeds the limit (stressed minus limit).', 'risk-metric', 'credit_risk', 'convention', NULL, 'excess,breach_amt', 'draft', NULL, NULL),
  ('excess_pct', 'breach excess percent', 'The percentage by which stressed exposure exceeds the limit.', 'risk-metric', 'credit_risk', 'convention', NULL, 'excesspct,breach_pct', 'draft', NULL, NULL),
  ('breach', 'limit breach', 'A condition where stressed exposure exceeds the approved limit for a line.', 'risk-metric', 'credit_risk', 'convention', NULL, 'breached', 'draft', NULL, NULL),
  ('agreement_group', 'agreement group', 'A grouping of related collateral agreements administered together for a counterparty relationship.', 'collateral', 'credit_risk', 'ISDA', NULL, 'agreementgroup,agreementgroupcode,groupname', 'draft', NULL, NULL),
  ('collateral_agreement_id', 'collateral agreement identifier', 'Unique identifier of a collateral (margin) agreement.', 'collateral', 'credit_risk', 'convention', NULL, 'collateralagreementid,agreementid', 'draft', NULL, NULL),
  ('agreement_type', 'agreement type', 'The legal type of an agreement (e.g. ISDA Master, CSA, GMRA, IM CSD).', 'collateral', 'credit_risk', 'ISDA', NULL, 'agreementtype', 'draft', NULL, NULL),
  ('agreement_category', 'agreement category', 'Classification of an agreement (e.g. regulatory IM, VM, legacy).', 'collateral', 'credit_risk', 'convention', NULL, 'agreementcategory', 'draft', NULL, NULL),
  ('agreement_status', 'agreement status', 'Lifecycle status of an agreement (e.g. active, pending, terminated).', 'collateral', 'credit_risk', 'convention', NULL, 'agreementstatus', 'draft', NULL, NULL),
  ('entity_code', 'entity code', 'Internal short code identifying a legal entity (TD or counterparty side).', 'counterparty', 'reference_data', 'convention', NULL, 'entitycode,shortcode,tdshortcode,cpshortcode,principalcode,counterpartycode', 'draft', NULL, NULL),
  ('goldtier_id', 'GoldTier identifier', 'Internal GoldTier reference identifier for a counterparty/entity.', 'counterparty', 'reference_data', 'convention', NULL, 'goldtierid', 'draft', NULL, NULL),
  ('csa_currency', 'CSA / collateral currency', 'The base currency in which collateral and exposure are denominated under an agreement.', 'collateral', 'credit_risk', 'ISDA', 'ISDA CSA', 'csaccy,collateralcurrency,basecurrency', 'draft', NULL, NULL),
  ('rounding', 'rounding amount', 'The increment to which collateral call amounts are rounded under a CSA.', 'collateral', 'credit_risk', 'ISDA', 'ISDA CSA', 'fixedroundingvalues,roundingvalues', 'draft', NULL, NULL),
  ('reciprocity', 'reciprocity', 'Whether collateral terms apply symmetrically (bilaterally) to both parties.', 'collateral', 'credit_risk', 'ISDA', NULL, 'reciprocity', 'draft', NULL, NULL),
  ('margin_call_frequency', 'margin call frequency', 'How often collateral is called/valued under an agreement (e.g. daily).', 'collateral', 'credit_risk', 'ISDA', NULL, 'mcfrequency,immcfrequency,legalreviewfrequency', 'draft', NULL, NULL),
  ('segregation', 'collateral segregation', 'Whether/how posted collateral is segregated (e.g. third-party custodian, title transfer).', 'collateral', 'credit_risk', 'Basel', 'BCBS-IOSCO', 'segtype,segregationtype', 'draft', NULL, NULL),
  ('linkage_set', 'linkage set', 'A set linking related agreements for netting/collateral purposes.', 'collateral', 'credit_risk', 'convention', NULL, 'linkageset', 'draft', NULL, NULL),
  ('simm', 'ISDA SIMM', 'ISDA Standard Initial Margin Model — the industry methodology for computing regulatory initial margin.', 'collateral', 'credit_risk', 'ISDA', 'ISDA SIMM', 'simmprincipalcalculationcurrency,simmcpcalculationcurrency', 'draft', NULL, NULL),
  ('regulatory_regime', 'regulatory regime', 'The margin regulation regime applicable to an agreement (e.g. UMR phase, EMIR, Dodd-Frank).', 'collateral', 'credit_risk', 'Basel', 'BCBS-IOSCO/UMR', 'regulatoryregime', 'draft', NULL, NULL),
  ('product_eligibility', 'product eligibility', 'The set of product types covered/eligible under an agreement.', 'collateral', 'credit_risk', 'ISDA', NULL, 'producteligibility,eligible', 'draft', NULL, NULL),
  ('im_calc_method', 'IM calculation method', 'Method used to compute initial margin (SIMM, grid/schedule).', 'collateral', 'credit_risk', 'ISDA', NULL, 'calculationmethod', 'draft', NULL, NULL),
  ('itm_exposure', 'in-the-money exposure', 'Exposure where positions have positive value to the institution (in-the-money).', 'risk-metric', 'credit_risk', 'convention', NULL, 'itmexposure', 'draft', NULL, NULL),
  ('otm_exposure', 'out-of-the-money exposure', 'Exposure where positions have negative value to the institution (out-of-the-money).', 'risk-metric', 'credit_risk', 'convention', NULL, 'otmexposure', 'draft', NULL, NULL),
  ('total_exposure', 'total exposure amount', 'The aggregate exposure amount under an agreement used to determine collateral requirements.', 'risk-metric', 'credit_risk', 'convention', NULL, 'totalexposureamount,basetotalexposureamount', 'draft', NULL, NULL),
  ('margin_call', 'margin call', 'A demand to post or return collateral to cover a change in exposure.', 'collateral', 'credit_risk', 'ISDA', NULL, 'callamount,basecallamount,reportingcallamount', 'draft', NULL, NULL),
  ('call_status', 'call status', 'Status of a margin call (e.g. agreed, disputed, pending).', 'collateral', 'credit_risk', 'convention', NULL, 'callstatus', 'draft', NULL, NULL),
  ('agreed_amount', 'agreed amount', 'The collateral amount agreed between parties for a call.', 'collateral', 'credit_risk', 'convention', NULL, 'agreedamount,counterpartyamount', 'draft', NULL, NULL),
  ('dispute', 'collateral dispute', 'A disagreement between parties over a margin call amount.', 'collateral', 'credit_risk', 'ISDA', NULL, 'disputes', 'draft', NULL, NULL),
  ('dispute_amount', 'dispute amount', 'The disputed portion of a margin call.', 'collateral', 'credit_risk', 'convention', NULL, 'disputeamount,reportingdisputeamount', 'draft', NULL, NULL),
  ('dispute_age', 'dispute age', 'How long a collateral dispute has been outstanding.', 'collateral', 'credit_risk', 'convention', NULL, 'disputeage', 'draft', NULL, NULL),
  ('collateral_value', 'collateral value', 'The reported/market value (NPV) of posted collateral.', 'collateral', 'credit_risk', 'convention', NULL, 'reportedcollateralvalue,collateralnpv', 'draft', NULL, NULL),
  ('asset_movement', 'collateral movement', 'A posting or return of a collateral asset (settlement of a call).', 'collateral', 'credit_risk', 'convention', NULL, 'movementtype,assetmovements', 'draft', NULL, NULL),
  ('asset_holding', 'collateral holding', 'A collateral asset currently held/posted under an agreement.', 'collateral', 'credit_risk', 'convention', NULL, 'assetholdings,assetid,assettype,positiontype', 'draft', NULL, NULL),
  ('settlement_instruction', 'settlement instruction', 'Standing instruction for where/how collateral is settled (accounts, custodian, bank).', 'collateral', 'credit_risk', 'convention', NULL, 'settlementinstructions,beneficiarybank,ultimatecustodian,accountnumber', 'draft', NULL, NULL),
  ('custodian', 'custodian', 'The institution holding/safekeeping posted collateral.', 'collateral', 'credit_risk', 'FIBO', 'FIBO: Custodian', 'ultimatecustodian', 'draft', NULL, NULL),
  ('pv', 'present value', 'The present value (mark-to-market) of a trade or position.', 'risk-metric', 'credit_risk', 'convention', NULL, 'presentvalue', 'draft', NULL, 'See also npv/mtm.'),
  ('valuation_date', 'valuation date', 'The date as of which a value/exposure is calculated.', 'date', 'shared', 'convention', NULL, 'valuationdate,collateralbalancedate,balancedate', 'draft', NULL, NULL),
  ('trade_id', 'trade identifier', 'A unique identifier for a trade in a source system.', 'market', 'trades', 'FpML', NULL, 'tradeidentifier,systemtradeid,externalid,instrumentid', 'draft', NULL, NULL),
  ('uti', 'Unique Trade Identifier', 'The globally unique identifier of a trade for regulatory reporting.', 'market', 'trades', 'ISO', 'UTI', 'uniquetradeid', 'draft', NULL, NULL),
  ('isda_product_type', 'ISDA product taxonomy', 'The ISDA product classification/taxonomy of a trade.', 'market', 'trades', 'ISDA', 'ISDA taxonomy', 'isdaproducttype,isdaproduct,producttype,systemproducttype', 'draft', NULL, NULL),
  ('buy_sell', 'buy/sell indicator', 'Whether the institution bought or sold in the trade.', 'market', 'trades', 'FpML', NULL, 'buysell,buyorsell', 'draft', NULL, NULL),
  ('strike_price', 'strike price', 'The exercise price of an option.', 'market', 'trades', 'FpML', NULL, 'strikeprice,putorcall', 'draft', NULL, NULL),
  ('pai', 'Price Alignment Interest', 'Interest paid/received on variation margin posted against collateralised/cleared derivatives.', 'collateral', 'credit_risk', 'convention', NULL, 'pairate', 'draft', NULL, NULL),
  ('repo', 'repurchase agreement', 'A sale of securities with an agreement to repurchase later; a financing trade governed by a GMRA.', 'market', 'trades', 'ISDA', 'GMRA', 'repotrades', 'draft', NULL, NULL),
  ('branch', 'branch', 'The booking branch/office of a party to a trade.', 'counterparty', 'reference_data', 'convention', NULL, 'branchname,partyabranchname,partybbranchname', 'draft', NULL, NULL),
  ('principal', 'principal', 'The institution''s own side (TD) in a collateral agreement, as opposed to the counterparty.', 'counterparty', 'credit_risk', 'ISDA', NULL, 'principalcode,principallei', 'draft', NULL, NULL),
  ('source_system', 'source system', 'The system of record from which a record originated.', 'general', 'shared', 'convention', NULL, 'sourcesystem', 'draft', NULL, NULL),
  ('settlement_date', 'settlement date', 'The date on which a trade or collateral movement settles.', 'date', 'shared', 'convention', NULL, 'settlementdate', 'draft', NULL, NULL),
  ('underlying', 'underlying', 'The reference asset/index underlying a derivative.', 'market', 'trades', 'FpML', NULL, 'underlying', 'draft', NULL, NULL),
  ('portfolio', 'portfolio', 'A grouping of positions for booking/management (e.g. IMS portfolio/desk).', 'market', 'trades', 'convention', NULL, 'imsportfolio,imsdesk', 'draft', NULL, NULL),
  ('direction', 'direction', 'The direction of a margin call or cash flow (call/return, pay/receive).', 'collateral', 'credit_risk', 'convention', NULL, NULL, 'draft', NULL, NULL),
  ('margin_type', 'margin type', 'Whether a margin amount is initial margin (IM) or variation margin (VM).', 'collateral', 'credit_risk', 'ISDA', NULL, 'margintype', 'draft', NULL, NULL),
  ('asset_class', 'asset class', 'The asset class of collateral or an underlying (e.g. cash, govvies, equity).', 'collateral', 'credit_risk', 'convention', NULL, 'assetclass', 'draft', NULL, NULL),
  ('rehypothecation', 'rehypothecation rights', 'Whether posted collateral may be reused (rehypothecated) by the receiving party.', 'collateral', 'credit_risk', 'ISDA', NULL, 'rehyp,rehypothecationrights', 'draft', NULL, NULL),
  ('collateral_status', 'collateral status', 'The status of a collateral position or balance.', 'collateral', 'credit_risk', 'convention', NULL, 'collateralstatus', 'draft', NULL, NULL),
  ('settlement_status', 'settlement status', 'The status of a collateral/trade settlement.', 'collateral', 'credit_risk', 'convention', NULL, 'settlementstatus', 'draft', NULL, NULL),
  ('haircut', 'collateral haircut', 'A percentage discount applied to the market value of collateral to reflect its risk/liquidity.', 'collateral', 'credit_risk', 'Basel', 'Basel CRE22', 'haircuts', 'draft', NULL, NULL),
  ('booked_amount', 'booked amount', 'The amount of a collateral movement/call as booked in the system.', 'collateral', 'credit_risk', 'convention', NULL, 'booked,bookedamount', 'draft', NULL, NULL),
  ('upfront', 'upfront payment', 'An upfront payment exchanged at trade inception (e.g. deal-level upfront).', 'market', 'trades', 'convention', NULL, 'deallevelupfronts,upfronts', 'draft', NULL, NULL),
  ('event', 'collateral event', 'A lifecycle event on an agreement or margin call (with event id/date/type).', 'collateral', 'credit_risk', 'convention', NULL, 'eventid,eventdate,eventsubtype,tradeevent', 'draft', NULL, NULL),
  ('par_value', 'par value', 'The nominal/face value of a security.', 'market', 'trades', 'FIBO', NULL, 'par', 'draft', NULL, NULL),
  ('product_class', 'product / asset class', 'A derivative product or asset class used to classify trades, limits and netting (IR, FX, equity, credit, commodity, etc.).', 'market', 'trades', 'ISDA', 'ISDA taxonomy', 'assetclass', 'draft', NULL, 'Captured as a qualifier on term-limit and netting fields.'),
  ('ir', 'interest rate', 'Interest-rate product class (swaps, options).', 'market', 'trades', 'ISDA', NULL, 'irs,iro', 'draft', NULL, NULL),
  ('ccs', 'cross-currency swap', 'Cross-currency swap product class.', 'market', 'trades', 'ISDA', NULL, NULL, 'draft', NULL, NULL),
  ('eqd', 'equity derivative', 'Equity derivative product class.', 'market', 'trades', 'ISDA', NULL, 'equity', 'draft', NULL, NULL),
  ('crd', 'credit derivative', 'Credit derivative product class (e.g. CDS).', 'market', 'trades', 'ISDA', NULL, 'credit', 'draft', NULL, NULL),
  ('commodity', 'commodity', 'Commodity product class.', 'market', 'trades', 'ISDA', NULL, 'comm,com,ngas', 'draft', NULL, 'Includes natural gas (ngas) and other energy/commodity sub-classes.'),
  ('fxo', 'FX option', 'Foreign-exchange option product class.', 'market', 'trades', 'ISDA', NULL, NULL, 'draft', NULL, NULL),
  ('pm', 'precious metals', 'Precious-metals product class.', 'market', 'trades', 'ISDA', NULL, NULL, 'draft', NULL, NULL),
  ('bo', 'BO (product class)', 'A product/asset class used for CSA coverage flags (csa_bo) in clients_report. Expansion intentionally left blank.', 'market', 'trades', 'convention', NULL, NULL, 'draft', NULL, 'Product class - sibling of irs/ccs/fx/eqd/crd/com/pm. Expansion to be verified in the product taxonomy / Acronyms reference.'),
  ('oes', 'OES (product class)', 'A product/asset class carrying its own credit sub-limit (oes_term_limit) in lines_report. Expansion intentionally left blank.', 'market', 'trades', 'convention', NULL, NULL, 'draft', NULL, 'Product class - sibling of ir/fx/ccs/eqd/crd/comm/ngas. Expansion to be verified in the product taxonomy / Acronyms reference.'),
  ('term_limit', 'product term limit', 'A credit limit applied to a specific product class and tenor.', 'risk-metric', 'credit_risk', 'convention', NULL, 'irtermlimit,fxtermlimit,ccstermlimit,irotermlimit,eqdtermlimit,crdtermlimit,commtermlimit,comtermlimit,ngastermlimit,oestermlimit,othertermlimit,botermlimit,pmtermlimit,ccstermlimit', 'draft', NULL, NULL),
  ('netting', 'netting', 'Whether exposures are netted (by product class or across products) under an agreement.', 'collateral', 'credit_risk', 'ISDA', 'ISDA Master', 'netfx,netfxo,netderv,xnetall,multibranchnetting,netting', 'draft', NULL, NULL),
  ('line_type', 'line type', 'The type/classification of a credit line.', 'general', 'credit_risk', 'convention', NULL, 'linetype', 'draft', NULL, NULL),
  ('days_since_expiry', 'days since expiry', 'Number of days since a line expired.', 'date', 'credit_risk', 'convention', NULL, 'dayssinceexpiry', 'draft', NULL, NULL),
  ('no_line_indicator', 'no-line indicator', 'Flag indicating no active line exists.', 'general', 'credit_risk', 'convention', NULL, 'nolineindicator,c2cnolineindicator,contnolineindicator', 'draft', NULL, NULL),
  ('parent_line_name', 'parent line name', 'The name of the parent line in a line hierarchy.', 'general', 'credit_risk', 'convention', NULL, 'parentlinename', 'draft', NULL, NULL),
  ('branch_locations', 'branch locations', 'Booking branches/locations associated with a line.', 'counterparty', 'reference_data', 'convention', NULL, 'branchlocations', 'draft', NULL, NULL),
  ('associated_clients', 'associated clients', 'Count of clients associated with a line.', 'counterparty', 'credit_risk', 'convention', NULL, 'numberofassociatedclients,numberofassociatedclient', 'draft', NULL, NULL),
  ('worst_rating', 'worst associated rating', 'The worst credit rating among clients associated with a line.', 'rating', 'credit_risk', 'convention', NULL, 'worstratingofassociatedclients,worstratingofassociatedc', 'draft', NULL, NULL),
  ('availability', 'availability', 'Remaining available limit headroom for a line/tenor.', 'risk-metric', 'credit_risk', 'convention', NULL, 'minavailability', 'draft', NULL, NULL),
  ('usage', 'usage', 'Used portion of a limit for a line/tenor (max usage over a window).', 'risk-metric', 'credit_risk', 'convention', NULL, 'maxusage', 'draft', NULL, NULL),
  ('excess_flag', 'excess flag', 'Flag indicating a line is in excess of its limit.', 'risk-metric', 'credit_risk', 'convention', NULL, 'excessflag', 'draft', NULL, NULL),
  ('excess_report_date', 'excess report date', 'The date a limit excess was reported.', 'date', 'credit_risk', 'convention', NULL, 'excessreportdate', 'draft', NULL, NULL),
  ('roll_off_limit', 'roll-off limit', 'A limit that steps down/rolls off over time.', 'risk-metric', 'credit_risk', 'convention', NULL, 'rollofflimit', 'draft', NULL, NULL),
  ('secured_limit', 'secured limit', 'Limit applicable to secured exposure.', 'risk-metric', 'credit_risk', 'convention', NULL, 'securedlimit', 'draft', NULL, NULL),
  ('gross_max_exposure', 'gross max exposure', 'The gross maximum exposure on a line.', 'risk-metric', 'credit_risk', 'convention', NULL, 'grossmaxexposure', 'draft', NULL, NULL),
  ('mark_to_market', 'mark-to-market', 'Current mark-to-market value of a line/position.', 'risk-metric', 'credit_risk', 'convention', NULL, 'marktomarket,mtm,negativemtm', 'draft', NULL, NULL),
  ('facility_id', 'facility identifier', 'Unique identifier of a credit facility.', 'general', 'credit_risk', 'convention', NULL, 'facilityid', 'draft', NULL, NULL),
  ('frr', 'facility risk rating', 'Internal facility risk rating (graded code, e.g. M/A); appears in lines_report immediately after facility_id.', 'rating', 'credit_risk', 'convention', NULL, NULL, 'draft', NULL, 'Confirmed from data: values M/A positioned after facility_id.'),
  ('credit_rating', 'credit rating', 'A credit rating value (internal or external).', 'rating', 'reference_data', 'convention', NULL, 'creditrating', 'draft', NULL, NULL),
  ('excess_percent', 'excess percent', 'Limit excess expressed as a percentage.', 'risk-metric', 'credit_risk', 'convention', NULL, 'excesspercent,excesspct', 'draft', NULL, NULL),
  ('last_modified_date', 'last modified date', 'The date a record was last modified.', 'date', 'shared', 'convention', NULL, 'lastmodifieddate', 'draft', NULL, NULL),
  ('business_date', 'business date', 'The business/as-of date of a record.', 'date', 'shared', 'convention', NULL, 'businessdate,asofdate,asof', 'draft', NULL, NULL),
  ('source', 'source', 'The source feed/system of a record.', 'general', 'shared', 'convention', NULL, 'sourcesystem', 'draft', NULL, NULL),
  ('counterparty_code', 'counterparty code', 'Internal code identifying a counterparty.', 'counterparty', 'reference_data', 'convention', NULL, 'counterpartycode,cptycode', 'draft', NULL, NULL),
  ('counterparty_long_name', 'counterparty long name', 'The full legal/long name of a counterparty.', 'counterparty', 'reference_data', 'convention', NULL, 'counterpartylongname,longname', 'draft', NULL, NULL),
  ('c2c_line', 'client-to-counterparty line', 'A client-to-counterparty (C2C) credit line identifier.', 'general', 'credit_risk', 'convention', NULL, 'c2cline', 'draft', NULL, NULL),
  ('cont_line', 'continuation line', 'A continuation (CONT) credit line identifier.', 'general', 'credit_risk', 'convention', NULL, 'contline', 'draft', NULL, NULL),
  ('immediate_parent', 'immediate parent', 'The immediate parent entity of a counterparty.', 'counterparty', 'reference_data', 'FIBO', NULL, 'immediateparent', 'draft', NULL, NULL),
  ('ultimate_parent', 'ultimate parent', 'The ultimate parent entity of a counterparty.', 'counterparty', 'reference_data', 'FIBO', NULL, 'ultimateparent', 'draft', NULL, NULL),
  ('cif_number', 'CIF (Customer Information File) number', 'The bank''s unique master client identifier; shows UNRESOLVED until the client is mapped, otherwise a customer number.', 'counterparty', 'reference_data', 'convention', NULL, 'cifnumber,cif,upcif', 'draft', NULL, 'up_cif = ultimate-parent CIF (the CIF of the counterparty''s ultimate parent).'),
  ('bis_code', 'BIS code', 'Bank for International Settlements / internal BIS code for an entity.', 'counterparty', 'reference_data', 'convention', NULL, 'biscode', 'draft', NULL, NULL),
  ('bis_eligible', 'BIS eligible', 'Flag indicating BIS eligibility.', 'counterparty', 'reference_data', 'convention', NULL, 'biseligible', 'draft', NULL, NULL),
  ('country_of_risk', 'country of risk', 'The country to which exposure risk is attributed.', 'counterparty', 'reference_data', 'convention', NULL, 'countryofrisk', 'draft', NULL, NULL),
  ('location_of_residence', 'location of residence', 'The counterparty''s country/location of residence.', 'counterparty', 'reference_data', 'convention', NULL, 'locationofresidence', 'draft', NULL, NULL),
  ('account_rating', 'account rating', 'Internal account-level credit rating.', 'rating', 'reference_data', 'convention', NULL, 'tdaccountrating', 'draft', NULL, NULL),
  ('country_risk_rating', 'country risk rating', 'Internal country risk rating.', 'rating', 'reference_data', 'convention', NULL, 'tdcountryofriskrating,countryofriskrating', 'draft', NULL, NULL),
  ('industry_risk_rating', 'industry risk rating', 'Internal industry risk rating.', 'rating', 'reference_data', 'convention', NULL, 'tdindustryriskrating,industryriskrating', 'draft', NULL, NULL),
  ('sic', 'SIC classification', 'Standard Industrial Classification of a counterparty (code/segment/group/industry/class).', 'counterparty', 'reference_data', 'ISO', 'SIC', 'sicclass,siccode,sicsegment,sicgroup,sicindustry', 'draft', NULL, NULL),
  ('bloomberg_classification', 'Bloomberg industry classification', 'Bloomberg industry classification (sector/group/subgroup) or ticker.', 'counterparty', 'reference_data', 'industry', 'Bloomberg BICS', 'bloombergticker,bloombergindustrysector,bloombergindustrygroup,bloombergindustrysubgroup,bloomberg', 'draft', NULL, NULL),
  ('sp_rating', 'S&P rating', 'Credit rating from S&P.', 'rating', 'reference_data', 'industry', 'S&P', 'sprating,sp', 'draft', NULL, NULL),
  ('moodys_rating', 'Moody''s rating', 'Credit rating from Moody''s.', 'rating', 'reference_data', 'industry', 'Moody''s', 'moodysrating,moodys,mdy', 'draft', NULL, NULL),
  ('composite_rating', 'composite rating', 'An internal composite rating (secured/unsecured/subordinated/preferred).', 'rating', 'credit_risk', 'convention', NULL, 'compositesecuredrating,compositeunsecuredrating,compositesubordinatedrating,compositepreferredrating,composite', 'draft', NULL, NULL),
  ('ifema', 'IFEMA', 'International Foreign Exchange Master Agreement.', 'collateral', 'credit_risk', 'industry', 'IFEMA', NULL, 'draft', NULL, NULL),
  ('agreement_group_code', 'agreement group code', 'Code identifying an agreement group.', 'collateral', 'credit_risk', 'ISDA', NULL, 'agreementgroupcode', 'draft', NULL, NULL),
  ('scenario_max', 'scenario stressed maximum', 'The maximum stressed exposure (PFE) produced under a given stress scenario; one column per scenario.', 'risk-metric', 'credit_risk', 'convention', NULL, 'cartormax,zeromax,c25max,c75max,str75max,onemax,prodmax,strmpr025max,maxofall,maxalllesscartor', 'draft', NULL, 'Scenario codes: cartor=base, zero=zero-corr, c25/c75=corr 0.25/0.75, one=corr 1.0, etc.'),
  ('percentage_of_impact', 'percentage of impact', 'Stressed maximum expressed as a ratio/percentage of the baseline (cartor) maximum.', 'risk-metric', 'credit_risk', 'convention', NULL, 'percentageofimpact,percentofimpact', 'draft', NULL, NULL),
  ('scenario_of_max', 'scenario of max', 'The scenario label that produced the overall maximum exposure.', 'risk-metric', 'credit_risk', 'convention', NULL, 'scenarioofmax', 'draft', NULL, NULL);
